export const categoryImages: Record<string, string> = {
  "Computer & Digital Skills": "/images/001.jpg",
  "Business & Administration": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
  "Customer Service & Hospitality": "/images/Intro-Home-page-new.png",
  "Marketing & Sales": "/images/SA-INNOVATION-COLLEGE2-scaled.jpg",
  "Management & Entrepreneurship": "/images/SA-INNOVATION-COLLEGE3-scaled.jpg",
  "Finance & Accounting": "/images/002.jpg",
  "Human Resources": "/images/blogs01.jpg",
  "Education & Training": "/images/sa-innovation-graduation.webp",
  "Early Childhood Development": "/images/blogs01.jpg",
  "Health & Safety": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
  "Security & Legal Studies": "/images/SA-INNOVATION-COLLEGE3-scaled.jpg",
  "Engineering": "/images/SA-INNOVATION-COLLEGE2-scaled.jpg",
  "IT & Software Development": "/images/001.jpg",
  "Health & Social Services": "/images/blogs01.jpg",
  "default": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
};

export const heroGradients: Record<string, string> = {
  "Computer & Digital Skills": "from-purple-900/80 via-purple-800/60",
  "Business & Administration": "from-blue-900/80 via-blue-800/60",
  "Customer Service & Hospitality": "from-orange-900/80 via-orange-800/60",
  "Marketing & Sales": "from-amber-900/80 via-amber-800/60",
  "Management & Entrepreneurship": "from-emerald-900/80 via-emerald-800/60",
  "Finance & Accounting": "from-green-900/80 via-green-800/60",
  "Human Resources": "from-teal-900/80 via-teal-800/60",
  "Education & Training": "from-indigo-900/80 via-indigo-800/60",
  "Early Childhood Development": "from-rose-900/80 via-rose-800/60",
  "Health & Safety": "from-red-900/80 via-red-800/60",
  "Security & Legal Studies": "from-blue-900/80 via-blue-800/60",
  "Engineering": "from-cyan-900/80 via-cyan-800/60",
  "IT & Software Development": "from-violet-900/80 via-violet-800/60",
  "Health & Social Services": "from-pink-900/80 via-pink-800/60",
};
