export const categoryImages: Record<string, string> = {
  "Computer & Digital Skills": "/images/001.jpg",
  "Business & Administration": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
  "Customer Service & Hospitality": "/images/Intro-Home-page-new.png",
  "Marketing & Sales": "/images/SA-INNOVATION-COLLEGE2-scaled.jpg",
  "Management & Entrepreneurship": "/images/SA-INNOVATION-COLLEGE3-scaled.jpg",
  "Finance & Accounting": "/images/002.jpg",
  "Human Resources": "/images/blogs01.jpg",
  "Education & Training": "/images/sa-innovation-graduation.webp",
  "Early Childhood Development": "/images/blogs01.jpg",
  "Health & Safety": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
  "Security & Legal Studies": "/images/SA-INNOVATION-COLLEGE3-scaled.jpg",
  "Engineering": "/images/SA-INNOVATION-COLLEGE2-scaled.jpg",
  "IT & Software Development": "/images/001.jpg",
  "Health & Social Services": "/images/blogs01.jpg",
  "default": "/images/SA-INNOVATION-COLLEGE-2-scaled.webp",
};

export const heroGradients: Record<string, string> = {
  "Computer & Digital Skills": "from-[var(--saic-navy-950)]/85 via-[var(--saic-navy-900)]/55",
  "Business & Administration": "from-[var(--saic-navy-950)]/85 via-[var(--saic-navy-700)]/55",
  "Customer Service & Hospitality": "from-[var(--saic-campaign-crimson-dark)]/85 via-[var(--saic-campaign-crimson)]/55",
  "Marketing & Sales": "from-[var(--saic-campaign-crimson)]/85 via-[var(--saic-gold-600)]/55",
  "Management & Entrepreneurship": "from-[var(--saic-navy-900)]/85 via-[var(--saic-campaign-crimson-dark)]/55",
  "Finance & Accounting": "from-[var(--saic-navy-950)]/85 via-[var(--saic-navy-700)]/55",
  "Human Resources": "from-[var(--saic-campaign-crimson-dark)]/85 via-[var(--saic-navy-900)]/55",
  "Education & Training": "from-[var(--saic-navy-900)]/85 via-[var(--saic-gold-600)]/55",
  "Early Childhood Development": "from-[var(--saic-campaign-crimson)]/85 via-[var(--saic-gold-600)]/55",
  "Health & Safety": "from-[var(--saic-campaign-crimson-dark)]/85 via-[var(--saic-campaign-crimson)]/55",
  "Security & Legal Studies": "from-[var(--saic-navy-950)]/85 via-[var(--saic-navy-700)]/55",
  "Engineering": "from-[var(--saic-navy-900)]/85 via-[var(--saic-campaign-crimson-dark)]/55",
  "IT & Software Development": "from-[var(--saic-navy-950)]/85 via-[var(--saic-campaign-crimson)]/55",
  "Health & Social Services": "from-[var(--saic-campaign-crimson-dark)]/85 via-[var(--saic-navy-900)]/55",
};
