"use client";

import { jsPDF } from "jspdf";
import Icon from "@/components/ui/Icon";

const BLUE: [number, number, number] = [27, 77, 142];
const DARK: [number, number, number] = [35, 35, 35];

export default function BlankApplicationDownload() {
  function download() {
    const doc = new jsPDF({ format: "a4", unit: "mm" });
    let page = 0;
    let y = 0;
    const footer = () => { doc.setDrawColor(220, 225, 232); doc.line(15, 283, 195, 283); doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(95, 95, 95); doc.text("SA Innovation College | SAIC-FRM-ADM-001 | Version 2026.1 | CONFIDENTIAL WHEN COMPLETED", 15, 289); doc.text(`Page ${page}`, 184, 289); };
    const newPage = (title?: string) => { if (page) footer(); doc.addPage(); page += 1; y = 18; doc.setFillColor(...BLUE); doc.rect(0, 0, 210, 14, "F"); doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.text("SA INNOVATION COLLEGE", 15, 9); if (title) { doc.setTextColor(...BLUE); doc.setFontSize(14); doc.text(title, 15, y); y += 9; } };
    const ensure = (height = 12) => { if (y + height > 276) newPage(); };
    const text = (value: string, size = 9, bold = false) => { ensure(7); doc.setTextColor(...DARK); doc.setFont("helvetica", bold ? "bold" : "normal"); doc.setFontSize(size); const lines = doc.splitTextToSize(value, 178); doc.text(lines, 16, y); y += lines.length * (size * 0.42) + 4; };
    const heading = (value: string) => { ensure(13); doc.setFillColor(235, 241, 250); doc.rect(15, y - 5, 180, 10, "F"); doc.setTextColor(...BLUE); doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.text(value, 18, y + 1); y += 12; };
    const line = (label: string, width = 178) => { ensure(11); doc.setTextColor(...DARK); doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.text(label, 16, y); doc.setDrawColor(125, 130, 138); doc.line(16, y + 4, 16 + width, y + 4); y += 11; };
    const checks = (value: string) => { ensure(8); doc.setTextColor(...DARK); doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.text(value, 16, y); y += 7; };
    const blanks = (count = 2) => { for (let i = 0; i < count; i += 1) line(""); };
    const table = (headers: string[], rows: number) => { ensure(12); doc.setFont("helvetica", "bold"); doc.setFontSize(7.5); doc.setTextColor(...BLUE); doc.text(headers.join("     |     "), 16, y); y += 5; for (let i = 0; i < rows; i += 1) line("________________________________________________________________________________________________"); };

    newPage();
    doc.setTextColor(...BLUE); doc.setFont("helvetica", "bold"); doc.setFontSize(20); doc.text("APPLICATION FOR ADMISSION - 2026", 16, 35); doc.setFont("helvetica", "italic"); doc.setFontSize(11); doc.text("Through Knowledge, We Grow Towards Excellence", 16, 44);
    text("147 Burger Avenue, 1st Floor, Barclays Centre | Lyttelton Manor, Centurion, 0157\nToll-Free: 0800 014 568 | WhatsApp: +27 72 773 3960\nEmail: info@sainnovationcollege.co.za | Website: www.sainnovationcollege.co.za", 9);
    heading("IMPORTANT APPLICATION INFORMATION"); text("Complete every section that applies. Write clearly in black or blue ink. Information must be accurate and match supporting documents. Submission does not guarantee admission; admission remains subject to programme requirements, verification, available space and College approval. Do not submit original documents. Incomplete applications may delay a decision. Keep a copy and quote your application reference number in all communication."); checks("Application method: [ ] Online   [ ] Email   [ ] Hand-delivered   [ ] Campus   [ ] Authorised representative"); checks("Application type: [ ] New   [ ] Returning student   [ ] Programme change   [ ] RPL   [ ] Re-admission"); checks("Intake: [ ] January 2026   [ ] April 2026   [ ] July 2026   [ ] September 2026   Other: ____________");
    heading("FOR OFFICE USE ONLY"); line("Application reference number:"); line("Student number:"); line("Date received: ______ / ______ / __________    Received by:"); checks("Channel: [ ] Online  [ ] Email  [ ] Walk-in  [ ] WhatsApp conversion  [ ] Agent  [ ] Other"); checks("Status: [ ] Draft  [ ] Submitted  [ ] Under review  [ ] Documents outstanding  [ ] Provisionally accepted  [ ] Accepted  [ ] Unsuccessful  [ ] Registered  [ ] Withdrawn"); line("Assigned admissions officer:");

    newPage("SECTION A: PROGRAMME SELECTION"); heading("A1. FIRST-CHOICE PROGRAMME"); line("Programme name:"); line("Programme code, if applicable:"); line("NQF level, if applicable:"); checks("Study mode: [ ] Full-time  [ ] Part-time  [ ] Online  [ ] Blended learning  [ ] Short learning programme"); checks("Attendance: [ ] Weekdays  [ ] Evenings  [ ] Saturdays  [ ] Flexible schedule"); line("Preferred start date: ______ / ______ / __________"); heading("A2. SECOND-CHOICE PROGRAMME"); line("Programme name:"); line("Programme code, if applicable:"); checks("Study mode: [ ] Full-time  [ ] Part-time  [ ] Online  [ ] Blended learning"); heading("A3. CAMPUS OR LEARNING LOCATION"); checks("[ ] Centurion Campus  [ ] Online  [ ] Workplace-based learning  [ ] Other approved location:"); line(""); heading("A4-A5. GOALS"); text("Reason for choosing this programme:"); blanks(3); text("Career goal or further-study opportunity:"); blanks(3);
    newPage("SECTION B: PERSONAL INFORMATION"); text("Information in this section must match your identity document or passport."); heading("B1. APPLICANT DETAILS"); checks("Title: [ ] Mr  [ ] Mrs  [ ] Miss  [ ] Ms  [ ] Dr  [ ] Prof  [ ] Other: __________"); line("Surname:"); line("First names in full:"); line("Preferred name:"); line("South African ID number:"); line("Passport number, if applicable:"); line("Passport country of issue:"); line("Passport expiry date: ______ / ______ / __________"); line("Date of birth: ______ / ______ / __________"); line("Nationality:"); line("Country of birth:"); checks("Gender: [ ] Female  [ ] Male  [ ] Prefer not to disclose  [ ] Other: __________"); checks("Marital status: [ ] Single  [ ] Married  [ ] Divorced  [ ] Widowed  [ ] Prefer not to disclose"); line("Home language:"); line("Preferred language of communication:"); heading("B2. CITIZENSHIP OR RESIDENCY"); checks("[ ] South African citizen  [ ] Permanent resident  [ ] Refugee/asylum seeker  [ ] International applicant  [ ] Other"); line("Permit type:"); line("Permit number:"); line("Permit expiry date: ______ / ______ / __________");
    newPage("SECTION C: CONTACT DETAILS"); heading("C1. APPLICANT CONTACT INFORMATION"); line("Primary cellphone number:"); line("Alternative cellphone number:"); line("WhatsApp number:"); line("Email address:"); checks("Preferred communication: [ ] Phone call  [ ] WhatsApp  [ ] SMS  [ ] Email"); heading("C2. RESIDENTIAL ADDRESS"); line("Street address:"); line("Suburb or township:"); line("City or town:"); line("Province:"); line("Postal code:"); line("Country:"); heading("C3. POSTAL ADDRESS"); checks("[ ] Same as residential address"); line("Postal address:"); line("City or town:"); line("Postal code:"); line("Country:"); heading("SECTION D: PARENT, GUARDIAN OR SPONSOR"); text("Complete if younger than 18 or another person is responsible for fees."); checks("Relationship: [ ] Parent  [ ] Legal guardian  [ ] Spouse  [ ] Relative  [ ] Employer  [ ] Sponsor  [ ] Other"); line("Title:"); line("Full name and surname:"); line("ID or passport number:"); line("Cellphone and alternative number:"); line("Email address:"); line("Residential address:"); line("Occupation and employer:"); line("Employer contact number:");
    newPage("SECTION E: EMERGENCY CONTACT AND NEXT OF KIN"); line("Full name and surname:"); line("Relationship to applicant:"); line("Primary cellphone number:"); line("Alternative cellphone number:"); line("Email address:"); line("Residential address:"); text("The person listed above may be contacted in an emergency."); heading("SECTION F: EDUCATIONAL BACKGROUND"); heading("F1. HIGHEST SCHOOL QUALIFICATION"); checks("Highest grade: [ ] Grade 9  [ ] Grade 10  [ ] Grade 11  [ ] Grade 12/Matric  [ ] Equivalent international  [ ] Other"); line("Name of school:"); line("Province or country:"); line("Year completed:"); line("Examination number:"); checks("Authority: [ ] DBE  [ ] IEB  [ ] Umalusi-recognised provider  [ ] International  [ ] Other"); checks("Matric status: [ ] Passed  [ ] Awaiting results  [ ] Currently completing  [ ] Did not complete  [ ] N/A"); heading("F2. SCHOOL SUBJECTS AND RESULTS"); table(["Subject", "Final result", "Year completed"], 8);
    newPage("SECTION F (CONTINUED): PRIOR STUDIES"); heading("F3. PREVIOUS POST-SCHOOL STUDIES"); checks("Previously studied at a college, university or training institution? [ ] Yes  [ ] No"); line("Institution name:"); line("Qualification or programme:"); line("Student number:"); line("Year started:"); line("Year completed/discontinued:"); checks("Status: [ ] Completed  [ ] In progress  [ ] Discontinued  [ ] Awaiting certification"); text("Reason for discontinuing, if applicable:"); blanks(2); heading("F4. ADDITIONAL QUALIFICATIONS"); table(["Institution", "Qualification/course", "Year", "Result/status"], 4); heading("SECTION G: RECOGNITION OF PRIOR LEARNING"); checks("Applying for RPL, credit transfer or exemption? [ ] Yes  [ ] No  [ ] Unsure - require guidance"); text("Relevant knowledge, experience or previous studies:"); blanks(3);
    newPage("SECTION H: EMPLOYMENT INFORMATION"); checks("Current status: [ ] Employed full-time  [ ] Employed part-time  [ ] Self-employed  [ ] Unemployed  [ ] Student  [ ] Volunteer  [ ] Other"); line("Employer or business name:"); line("Position or occupation:"); line("Employment start date: ______ / ______ / __________"); line("Employer address:"); line("Supervisor name and contact:"); line("Employer email:"); checks("Employer supporting studies? [ ] Yes  [ ] No  [ ] Partially"); heading("SECTION I: FUNDING AND PAYMENT"); checks("Payment method: [ ] Self-funded  [ ] Parent/guardian  [ ] Employer  [ ] Bursary  [ ] Scholarship  [ ] Government funding  [ ] Payment plan  [ ] Other sponsor  [ ] Not confirmed"); line("Person/organisation responsible:"); line("ID or registration number:"); line("Relationship:"); line("Contact number and email:"); line("Billing address:"); checks("Purchase order, sponsorship or bursary confirmation? [ ] Yes  [ ] No  [ ] N/A"); line("Reference number:"); text("Completing this application does not confirm funding. Review official fees, deadlines and refund conditions before registration.");
    newPage("SECTION J: SUPPORT, TECHNOLOGY AND PROGRAMME REQUIREMENTS"); text("Information in the support section is confidential and used to assess appropriate assistance."); checks("Support requirement? [ ] Yes  [ ] No  [ ] Prefer to discuss privately"); checks("Support area: [ ] Physical access  [ ] Visual  [ ] Hearing  [ ] Learning  [ ] Assessment  [ ] Mental health  [ ] Chronic condition  [ ] Other"); text("Support required:"); blanks(3); checks("Student-support representative contact: [ ] Yes  [ ] No"); heading("SECTION K: TECHNOLOGY AND ONLINE LEARNING"); checks("Devices: [ ] Desktop  [ ] Laptop  [ ] Tablet  [ ] Smartphone  [ ] Shared computer  [ ] None"); checks("Internet: [ ] Reliable home  [ ] Mobile data  [ ] Workplace  [ ] Public/community  [ ] Limited  [ ] None"); checks("Digital skills: [ ] Beginner  [ ] Basic  [ ] Intermediate  [ ] Advanced"); checks("Active email independently accessible? [ ] Yes  [ ] No"); heading("SECTION L: ADDITIONAL PROGRAMME REQUIREMENTS"); checks("Driver licence: [ ] Yes  [ ] No  [ ] Learner's licence  [ ] N/A    Code: __________   Expiry: __________"); checks("Criminal-record/suitability assessment relevant? [ ] Yes  [ ] No  [ ] Unsure"); checks("Willing to submit where formally required? [ ] Yes  [ ] No  [ ] N/A"); checks("Medical/fitness requirements acknowledged: [ ] Yes  [ ] No  [ ] N/A");
    newPage("SECTION M: DOCUMENTS, MARKETING AND MOTIVATION"); text("Attach clear copies applicable to your application. Do not submit originals."); table(["Document", "Attached", "Outstanding", "N/A"], 15); text("Certified ID | Certified passport | Valid permit | Matric certificate | Latest results | Previous qualifications | Transcript | Proof of address | CV | Driver licence | Sponsorship/bursary | Purchase order | Proof of payment | RPL evidence | Other"); heading("SECTION N: HOW DID YOU HEAR ABOUT US?"); checks("[ ] Facebook  [ ] Instagram  [ ] TikTok  [ ] LinkedIn  [ ] Google  [ ] Website  [ ] WhatsApp  [ ] Friend/family  [ ] Student  [ ] School  [ ] Exhibition  [ ] Employer  [ ] Flyer  [ ] Radio  [ ] Community organisation  [ ] Other"); line("Referrer name, if applicable:"); heading("SECTION O: APPLICANT MOTIVATION"); blanks(6);
    newPage("SECTION P: DECLARATIONS AND SECTION Q: POPIA CONSENT"); text("Read and initial each statement."); ["Information and supporting documents are true, complete and accurate.", "The College may verify relevant information and documents subject to applicable law.", "Application does not guarantee admission, funding, certification, placement or employment.", "Admission is subject to verified requirements, documents, capacity and academic rules.", "I will review and accept the official fee schedule, payment terms and refund policy before registration.", "I will notify the College if contact, sponsorship or other material information changes.", "Materially false or misleading information may result in rejection or registration review."].forEach((item, index) => { text(`P${index + 1}. ${item}`); line("Applicant initials:", 55); }); heading("PRIVACY AND POPIA CONSENT"); text("The College processes personal information to assess and administer applications, verify identity and documents, communicate outcomes, provide student support, maintain regulatory records, manage fees and protect applicants and the College. Information will be protected using reasonable measures and retained for an appropriate operational, regulatory or legal period. Applicants may request access to or correction through the official privacy contact channel."); checks("Required processing: [ ] I consent"); checks("Application communication: [ ] Email  [ ] SMS  [ ] WhatsApp  [ ] Phone call"); checks("Optional marketing: [ ] Yes  [ ] No"); checks("Third-party verification: [ ] I consent  [ ] Contact me before additional verification");
    newPage("SECTION R: APPLICANT, GUARDIAN AND SPONSOR SIGNATURES"); text("I confirm that I have read and understood this form and agree to the declarations and consents selected above."); line("Applicant full name:"); line("Applicant signature:"); line("Date: ______ / ______ / __________"); line("Place signed:"); checks("Electronic application: [ ] My electronic signature and submission represent my approval"); line("Electronic signature or typed full name:"); line("Submission date and time:"); heading("PARENT OR LEGAL GUARDIAN CONSENT"); text("Complete if the applicant is younger than 18 years. I confirm I am the applicant's parent or lawful guardian and consent to this application being considered."); line("Parent/guardian name:"); line("ID or passport number:"); line("Relationship:"); line("Contact number:"); line("Signature:"); line("Date: ______ / ______ / __________"); heading("SPONSOR OR ACCOUNT HOLDER ACKNOWLEDGEMENT"); line("Sponsor/account holder:"); line("Authorised representative and position:"); line("Signature:"); line("Date: ______ / ______ / __________"); line("Official stamp, if applicable:");
    newPage("SECTION U: ADMISSIONS ASSESSMENT - OFFICE USE ONLY"); heading("U1. APPLICATION COMPLETENESS"); checks("[ ] Personal information  [ ] Contact verified  [ ] Programme selected  [ ] Entry requirements checked"); checks("[ ] Education reviewed  [ ] ID received  [ ] Academic documents  [ ] Funding recorded  [ ] Declaration signed  [ ] POPIA consent  [ ] Additional requirements"); heading("U2. DOCUMENT VERIFICATION"); table(["Document", "Received", "Verified", "Date/expiry", "Notes"], 7); heading("U3. ENTRY REQUIREMENT ASSESSMENT"); checks("[ ] Meets requirements  [ ] Provisionally meets  [ ] Assessment required  [ ] RPL review  [ ] Alternative programme  [ ] Does not currently meet"); text("Assessment notes:"); blanks(3); heading("U4. ADMISSIONS RECOMMENDATION"); checks("[ ] Accept  [ ] Provisionally accept  [ ] Request documents  [ ] Academic assessment  [ ] RPL assessment  [ ] Waiting list  [ ] Alternative  [ ] Decline"); text("Reason or conditions:"); blanks(2); line("Officer name and signature:"); line("Date: ______ / ______ / __________"); heading("U5. ACADEMIC APPROVAL"); checks("[ ] Approved  [ ] Conditionally approved  [ ] Not approved  [ ] Further information"); text("Comments/conditions:"); blanks(2); line("Reviewer signature and date:");
    newPage("SECTION V: REGISTRATION OUTCOME AND SUBMISSION"); line("Final programme:"); line("Programme code:"); line("Study mode:"); line("Intake:"); line("Start date: ______ / ______ / __________"); line("Student number:"); checks("Registration: [ ] Awaiting payment  [ ] Awaiting documents  [ ] Provisionally registered  [ ] Fully registered  [ ] Cancelled"); checks("Offer letter issued: [ ] Yes  [ ] No     Date issued: __________________"); checks("Registration agreement signed: [ ] Yes  [ ] No"); checks("Finance clearance: [ ] Approved  [ ] Pending  [ ] N/A"); line("Processed by:"); line("Date completed: ______ / ______ / __________"); heading("APPLICATION SUBMISSION INSTRUCTIONS"); text("Online: complete and submit through the official website. You should receive a reference number, confirmation, downloadable copy, document checklist and tracking instructions. Email: send the completed form and supporting documents to info@sainnovationcollege.co.za with subject 2026 APPLICATION - FULL NAME - PROGRAMME. Hand delivery: SA Innovation College, 147 Burger Avenue, 1st Floor, Barclays Centre, Lyttelton Manor, Centurion, 0157. Operating hours Monday-Friday 08:00-17:00. Do not send passwords, card PINs or original identity documents through WhatsApp or ordinary email."); heading("APPLICATION RECEIPT"); line("Applicant name:"); line("Programme:"); line("Reference number:"); line("Date received:"); line("Received by:"); line("Outstanding documents:"); line("Admissions office stamp:"); text("SA Innovation College | Through Knowledge, We Grow Towards Excellence | SAIC-FRM-ADM-001 | Version 2026.1 | Effective date: __________ | Next review: __________", 8, true);
    footer(); doc.deletePage(1); doc.save("SAIC-FRM-ADM-001-2026.1-Application-Form.pdf");
  }
  return <button type="button" onClick={download} className="inline-flex items-center gap-2 rounded-xl bg-[var(--color-primary)] px-4 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:shadow-md"><Icon name="arrow-down-tray" size={4} />Download blank form</button>;
}